//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanQuanAo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiaChiGiaoHang
    {
        public int MaDiaChi { get; set; }
        public int MaKhachHang { get; set; }
        public string DiaChiDong1 { get; set; }
        public string DiaChiDong2 { get; set; }
        public string ThanhPho { get; set; }
        public string TinhThanh { get; set; }
        public string QuocGia { get; set; }
        public string MaBuuDien { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
    }
}
